#!/bin/sh

# generate a temporary private key
rm -f /tmp/kcm.key
openssl genrsa -out /tmp/kcm.key 1024

# generate a temporary public certificate
rm -f /tmp/kcm.crt
cat << EOF | openssl req -new -x509 -key /tmp/kcm.key -out /tmp/kcm.crt -days 1
US
Pennsylvania
Pittsburgh
Carnegie Mellon University
Kimberley Project
Kimberley
kimberley@kimberley.cs.cmu.edu
EOF

# run kcm with these params
kcm /tmp/kcm.crt /tmp/kcm.key
