#!/bin/sh
#
#  Kimberley Display Control Manager
#
#  Copyright (c) 2007-2008 Carnegie Mellon University
#  All rights reserved.
#
#  Kimberley is free software: you can redistribute it and/or modify
#  it under the terms of version 2 of the GNU General Public License
#  as published by the Free Software Foundation.
#
#  Kimberley is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with Kimberley. If not, see <http://www.gnu.org/licenses/>.
#

# generate a temporary private key
rm -f /tmp/kcm.key
openssl genrsa -out /tmp/kcm.key 1024

# generate a temporary public certificate
rm -f /tmp/kcm.crt
cat << EOF | openssl req -new -x509 -key /tmp/kcm.key -out /tmp/kcm.crt -days 1
US
Pennsylvania
Pittsburgh
Carnegie Mellon University
Kimberley Project
Kimberley
kimberley@kimberley.cs.cmu.edu
EOF

# run kcm with these params
kcm /tmp/kcm.crt /tmp/kcm.key
